behaviors:
  BallAgentStage2:
    trainer_type: sac
    hyperparameters:
      buffer_init_steps: 0
      tau: 0.005
      steps_per_update: 10.0
      save_replay_buffer: false
      init_entcoef: 0.5
      reward_signal_steps_per_update: 10.0
    network_settings:     
      normalize: true
      hidden_units: 128
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
            gamma: 0.99
            strength: 1.0
    keep_checkpoints: 20     
    max_steps: 20000000
    time_horizon: 128
    summary_freq: 10000
    threaded: true
    
        
