behaviors:
  BallAgentStage2:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128      
      buffer_size: 5000
      learning_rate: 3.0e-4
      beta: 1.0e-3
      epsilon: 0.15    
      lambd: 0.92
      num_epoch: 3     
      learning_rate_schedule: linear
    network_settings:     
      normalize: true
      hidden_units: 128
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
            gamma: 0.99
            strength: 1.0
    keep_checkpoints: 5     
    max_steps: 2.0e6
    time_horizon: 128
    summary_freq: 50000
    threaded: true
    
        
